### ISSUE TITLE
virtual-repeat(tab): null pointer reference when elements are removed from the page

### ISSUE THREAD

**Issue by sikorsky555** [angular/material#10328]
**Actual Behavior**:
 -  `What is the issue? *` Errors are thrown when navigating away from components
 -  `What is the expected behavior?` No errors should be thrown

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.1.0
 -  `Angular Material Version:` 1.5.8

**Additional Information**:
 -  `Browser Type: *` Internet Explorer
 -  `Browser Version: *`11
 -  `OS: *` Windows 10
 -  `Stack Traces:`

TypeError: Unable to get property 'querySelector' of undefined or null reference
   at getElements (http://10.75.96.29:3000/console/apps/UICORE/js/external.js:98026:5)
   at updateInkBarStyles (http://10.75.96.29:3000/console/apps/UICORE/js/external.js:98331:5)
   at Anonymous function (http://10.75.96.29:3000/console/apps/UICORE/js/external.js:91296:11)
   at Anonymous function (http://10.75.96.29:3000/console/apps/UICORE/js/external.js:29687:11)
   at completeOutstandingRequest (http://10.75.96.29:3000/console/apps/UICORE/js/external.js:16039:7)
   at Anonymous function (http://10.75.96.29:3000/console/apps/UICORE/js/external.js:16318:7) undefined

TypeError: Unable to get property 'querySelector' of undefined or null reference
   at getElements (http://10.75.96.29:3000/console/apps/UICORE/js/external.js:98026:5)
   at updatePagingWidth (http://10.75.96.29:3000/console/apps/UICORE/js/external.js:98147:5)
   at updatePagination (http://10.75.96.29:3000/console/apps/UICORE/js/external.js:98138:5)
   at Anonymous function (http://10.75.96.29:3000/console/apps/UICORE/js/external.js:98005:7)
   at Anonymous function (http://10.75.96.29:3000/console/apps/UICORE/js/external.js:91557:13)
   at processQueue (http://10.75.96.29:3000/console/apps/UICORE/js/external.js:91554:9)
   at Anonymous function (http://10.75.96.29:3000/console/apps/UICORE/js/external.js:29687:11)
   at completeOutstandingRequest (http://10.75.96.29:3000/console/apps/UICORE/js/external.js:16039:7)
   at Anonymous function (http://10.75.96.29:3000/console/apps/UICORE/js/external.js:16318:7) undefined

Unable to get property 'appendChild' of undefined or null reference virtualRepeat.js (824, 1).
This is within the getBlock_ function.

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. The CodePen demo of the issue is **required**.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
