### ISSUE TITLE
md-select: prototypical inheritance and duplicate values

### ISSUE THREAD

**Issue by philipyun** [angular/material#10380]
**Actual Behavior**:
 -  `What is the issue? *` When using prototypical inheritance and property defining on Object, the name of the value assigned to object cannot be used as an md-option.  When used, it cannot be selected.  The name will show up in the drop down list but will not select properly
 -  `What is the expected behavior?` Should be able to select anything in md-option list, as long as the ng-value is not repeated in the md-option list.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/philipyun/pen/apaBpL
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.6.1
 -  `Angular Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *` Chrome/Firefox/Safari
 -  `Browser Version: *` latest
 -  `OS: *` Mac OS Sierra
 -  `Stack Traces:`

```
Error: Duplicate md-option values are not allowed in a select. Duplicate value 'inherited' found.
    at SelectMenuController.self.addOption (https://cdnjs.cloudflare.com/ajax/libs/angular-material/1.1.3/angular-material.js:19479:15)
    at setOptionValue (https://cdnjs.cloudflare.com/ajax/libs/angular-material/1.1.3/angular-material.js:19651:18)
    at Scope.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.js:17814:23)
    at Scope.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.js:18080:24)
    at bootstrapApply (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.js:1841:15)
    at Object.invoke (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.js:4842:19)
    at doBootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.js:1839:14)
    at bootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.js:1859:12)
    at angularInit (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.js:1744:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.js:32977:5
```

This is clearly caused by the notion and common practice that a simple object can be used as a Map structure.  When someone overrides or adds properties to the base Object definition, those values limit the possible values bound to md-option's ng-value attribute.

The selector controller defines two pseudo maps starting at [line 674 in src/components/select/select.js](https://github.com/angular/material/blob/master/src/components/select/select.js#L674)

```
    // selected is an object with keys matching all of the selected options' hashed values
    self.selected = {};
    // options is an object with keys matching every option's hash value,
    // and values matching every option's controller.
    self.options = {};
```

In [line 842](https://github.com/angular/material/blob/master/src/components/select/select.js#L842) we have the following segment:

```
    self.addOption = function(hashKey, optionCtrl) {
      if (angular.isDefined(self.options[hashKey])) {
        throw new Error('Duplicate md-option values are not allowed in a select. ' +
          'Duplicate value "' + optionCtrl.value + '" found.');
      }
```
The check on `angular.isDefined(self.options[hashKey])` will check the entire global namespace rather than the local one.  Thus if I add a property to object like so:

```
Object.defineProperty(Object.prototype, "example", {
    value: "sample_text"
})
```

Then the following md-option becomes forbidden:

```
<md-option ng-value="'example'">Cannot select this option </md-option>
```

By converting these (and all references) to map semantics, we have a local namespace to check repeated values on, instead of checking the entire global environment's namespace.

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by philipyun** [comment]
I have implemented my belief of a possible fix, PR #10381
