### ISSUE TITLE
OriginX error while using angular/material 2 autocomplete

### ISSUE THREAD

**Issue by AyzPat** [angular/material#10553]
**Getting this error using ng2 webpack**
error_handler.js:61 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:61
next @ application_ref.js:375
schedulerFn @ async.js:101
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:87
NgZone.triggerError @ ng_zone.js:334
onHandleError @ ng_zone.js:295
ZoneDelegate.handleError @ zone.js:246
Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:345
error_handler.js:62 TypeError: Cannot read property 'originX' of undefined
    at ConnectedPositionStrategy.Array.concat.ConnectedPositionStrategy._getOriginConnectionPoint (http://localhost:4007/assets/dist/0.chunk.js:6265:16)
    at ConnectedPositionStrategy.Array.concat.ConnectedPositionStrategy.recalculateLastPosition (http://localhost:4007/assets/dist/0.chunk.js:6197:32)
    at MdAutocompleteTrigger.Array.concat.MdAutocompleteTrigger._resetPanel (http://localhost:4007/assets/dist/0.chunk.js:4860:32)
    at SwitchMapSubscriber.project (http://localhost:4007/assets/dist/0.chunk.js:4789:19)
    at SwitchMapSubscriber._next (http://localhost:4007/assets/dist/vendor.dll.js:94487:27)
    at SwitchMapSubscriber.Subscriber.next (http://localhost:4007/assets/dist/vendor.dll.js:457:18)
    at MergeAllSubscriber.OuterSubscriber.notifyNext (http://localhost:4007/assets/dist/vendor.dll.js:642:26)
    at InnerSubscriber._next (http://localhost:4007/assets/dist/vendor.dll.js:85298:21)
    at InnerSubscriber.Subscriber.next (http://localhost:4007/assets/dist/vendor.dll.js:457:18)
    at FirstSubscriber._emitFinal (http://localhost:4007/assets/dist/vendor.dll.js:47638:25)
    at FirstSubscriber._emit (http://localhost:4007/assets/dist/vendor.dll.js:47621:14)
    at FirstSubscriber._next (http://localhost:4007/assets/dist/vendor.dll.js:47600:18)
    at FirstSubscriber.Subscriber.next (http://localhost:4007/assets/dist/vendor.dll.js:457:18)
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:4007/assets/dist/vendor.dll.js:42094:52)
    at SafeSubscriber.__tryOrUnsub (http://localhost:4007/assets/dist/vendor.dll.js:591:16)
    at SafeSubscriber.next (http://localhost:4007/assets/dist/vendor.dll.js:540:22)
    at Subscriber._next (http://localhost:4007/assets/dist/vendor.dll.js:493:26)
    at Subscriber.next (http://localhost:4007/assets/dist/vendor.dll.js:457:18)
    at EventEmitter.Subject.next (http://localhost:4007/assets/dist/vendor.dll.js:4237:25)
    at EventEmitter.emit (http://localhost:4007/assets/dist/vendor.dll.js:42080:76)
    at http://localhost:4007/assets/dist/vendor.dll.js:30231:85
    at ZoneDelegate.invoke (http://localhost:4007/assets/dist/polyfills.dll.js:4162:26)
    at Zone.run (http://localhost:4007/assets/dist/polyfills.dll.js:4033:43)
    at NgZone.runOutsideAngular (http://localhost:4007/assets/dist/vendor.dll.js:30151:76)
    at NgZone.checkStable (http://localhost:4007/assets/dist/vendor.dll.js:30231:30)
    at NgZone.onLeave (http://localhost:4007/assets/dist/vendor.dll.js:30301:14)
    at Object.onInvokeTask (http://localhost:4007/assets/dist/vendor.dll.js:30254:27)
    at ZoneDelegate.invokeTask (http://localhost:4007/assets/dist/polyfills.dll.js:4194:40)
    at Zone.runTask (http://localhost:4007/assets/dist/polyfills.dll.js:4071:47)
    at HTMLInputElement.ZoneTask.invoke (http://localhost:4007/assets/dist/polyfills.dll.js:4265:33)
  -------------   Elapsed: 10283 ms; At: Fri Mar 31 2017 18:07:58 GMT+0530 (IST)   -------------  
    at getStacktraceWithUncaughtError (http://localhost:4007/assets/dist/polyfills.dll.js:3790:12) [angular]
    at new LongStackTrace (http://localhost:4007/assets/dist/polyfills.dll.js:3784:22) [angular]
    at Object.onScheduleTask (http://localhost:4007/assets/dist/polyfills.dll.js:3840:18) [angular]
    at ZoneDelegate.scheduleTask (http://localhost:4007/assets/dist/polyfills.dll.js:4172:49) [angular]
    at Zone.scheduleEventTask (http://localhost:4007/assets/dist/polyfills.dll.js:4091:39) [angular]
    at zoneAwareAddListener (http://localhost:4007/assets/dist/polyfills.dll.js:5146:14) [angular]
    at HTMLInputElement.addEventListener (eval at createNamedFn (http://localhost:4007/assets/dist/polyfills.dll.js:5252:17), <anonymous>:3:43) [angular]
    at DomEventsPlugin.addEventListener (http://localhost:4007/assets/dist/vendor.dll.js:64121:17) [angular]
    at EventManager.addEventListener (http://localhost:4007/assets/dist/vendor.dll.js:14568:23) [angular]
    at DomRenderer.listen (http://localhost:4007/assets/dist/vendor.dll.js:45349:48) [angular]
    at DebugDomRenderer.listen (http://localhost:4007/assets/dist/vendor.dll.js:78150:31) [angular]
    at subscribeToRenderElement (http://localhost:4007/assets/dist/vendor.dll.js:29390:40) [angular]
    at CompiledTemplate.proxyViewClass.View_BasicInfoComponent0.createInternal (/DashboardModule/BasicInfoComponent/component.ngfactory.js:3019:22) [angular]
    at CompiledTemplate.proxyViewClass.AppView.create (http://localhost:4007/assets/dist/vendor.dll.js:79480:21) [angular]
    at CompiledTemplate.proxyViewClass.DebugAppView.create (http://localhost:4007/assets/dist/vendor.dll.js:79932:44) [angular]
    at CompiledTemplate.proxyViewClass.View_BasicInfoComponent_Host0.createInternal (/DashboardModule/BasicInfoComponent/host.ngfactory.js:16:19) [angular]
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4007/assets/dist/vendor.dll.js:79493:21) [angular]
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:4007/assets/dist/vendor.dll.js:79949:52) [angular]
    at ComponentFactory.create (http://localhost:4007/assets/dist/vendor.dll.js:42338:25) [angular]
    at ViewContainerRef_.createComponent (http://localhost:4007/assets/dist/vendor.dll.js:59291:62) [angular]
    at RouterOutlet.activate (http://localhost:4007/assets/dist/vendor.dll.js:65111:40) [angular]
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:4007/assets/dist/vendor.dll.js:23665:16) [angular]
    at ActivateRoutes.activateRoutes (http://localhost:4007/assets/dist/vendor.dll.js:23632:26) [angular]
    at http://localhost:4007/assets/dist/vendor.dll.js:23568:58 [angular]
    at Array.forEach (native) [angular]****

**Comment by ThomasBurleson** [comment]
Please report this is on the `github.com/angular/material2` repo
