### ISSUE TITLE
Dialog: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by row1** [angular/material#1061]
I am getting an error about length not being defined:
```
TypeError: Cannot read property 'length' of undefined
    at Object.onRemove (http://localhost:3000/bower/angular-material.js:2662:28)
    at Object.InterimElementFactory.self.remove (http://localhost:3000/bower/angular-material.js:1082:31)
    at Object.cancel (http://localhost:3000/bower/angular-material.js:1013:42)
    at Object.show (http://localhost:3000/bower/angular-material.js:967:19)
    at Object.showInterimElement [as show] (http://localhost:3000/bower/angular-material.js:910:38)
````

I guess the statements could just be swapped around?
````
options.popInTarget.length && options.popInTarget
````
https://github.com/angular/bower-material/blob/ef4dcccc876f6c36dd3842fcbcfa8389bc5bc522/modules/closure/dialog/dialog.js#L348

**Comment by ThomasBurleson** [comment]
@row1 - oops, our code review missed that one.
