### ISSUE TITLE
gulp docs does not work 

### ISSUE THREAD

**Issue by yjbyf** [angular/material#10634]
run  'gulp docs',then get error output as following

`➜  material git:(master) ✗ gulp docs
[13:37:20] Using gulpfile ~/yoApps/lib/material/gulpfile.js
[13:37:20] Starting 'build-scss'...
[13:37:20] Building css files...
[13:37:20] Starting 'build-js'...
[13:37:20] building js files...
[13:37:20] Starting 'docs-html2js'...
[13:37:20] Starting 'demos'...
[13:37:21] Finished 'docs-html2js' after 322 ms
WARN: Output exceeds 32000 characters
[13:37:43] Finished 'build-js' after 22 s
[13:37:43] Finished 'build-scss' after 22 s
[13:37:43] Starting 'build'...
[13:37:43] Finished 'build' after 46 μs
[13:37:43] Starting 'docs-generate'...
[13:37:43] Starting 'docs-js-dependencies'...
[13:37:43] Starting 'docs-css-dependencies'...
info:    running processor: readFilesProcessor
info:    running processor: extractJSDocCommentsProcessor
info:    running processor: parseTagsProcessor
info:    running processor: filterNgDocsProcessor
info:    running processor: extractTagsProcessor
info:    running processor: codeNameProcessor
info:    running processor: computeIdsProcessor
info:    running processor: memberDocsProcessor
info:    running processor: moduleDocsProcessor
info:    running processor: providerDocsProcessor
info:    running processor: collectKnownIssuesProcessor
info:    running processor: computePathsProcessor
info:    running processor: componentsGenerateProcessor
info:    running processor: indexPageProcessor
info:    running processor: buildConfigProcessor
[13:37:46] Finished 'docs-css-dependencies' after 2.62 s
[13:37:46] Finished 'docs-js-dependencies' after 2.63 s
info:    running processor: contentProcessor
info:    running processor: renderDocsProcessor
error:   Error: Failed to render - doc "module:material.components.autocomplete.directive:mdAutocomplete" (directive)  - from file "src/components/autocomplete/js/autocompleteDirective.js" - starting at line 5, ending at line 224

Original Error:

Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/lib/macros.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/lib/params.template.html) [Line 12, Column 17]
  Error: Unable to call `paramTable`, which is undefined or falsey
    at Object.exports.prettifyError (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/lib.js:34:15)
    at /Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:486:31
    at new_cls.root [as rootRenderFunc] (<anonymous>:31:3)
    at new_cls.render (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:479:15)
    at /Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:312:35
    at createTemplate (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:234:25)
    at handle (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:249:25)
    at /Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:263:21
    at next (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/lib.js:207:13)
    at Object.exports.asyncIter (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/lib.js:214:5)
    at new_cls.getTemplate (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:242:17)
    at new_cls.render (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:304:14)
    at render (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni-packages/nunjucks/services/nunjucks-template-engine.js:35:23)
    at Object.<anonymous> (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni-packages/base/processors/render-docs.js:50:33)
    at Array.forEach (native)
    at Object.process [as $process] (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni-packages/base/processors/render-docs.js:42:12)
    at /Users/baiyufan/yoApps/lib/material/node_modules/dgeni/lib/Dgeni.js:179:54
    at _fulfilled (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:796:13)
    at /Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:604:44
    at runSingle (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:137:13)
    at flush (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

    at Object.<anonymous> (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni-packages/base/processors/render-docs.js:53:17)
    at Array.forEach (native)
    at Object.process [as $process] (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni-packages/base/processors/render-docs.js:42:12)
    at /Users/baiyufan/yoApps/lib/material/node_modules/dgeni/lib/Dgeni.js:179:54
    at _fulfilled (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:796:13)
    at /Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:604:44
    at runSingle (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:137:13)
    at flush (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

error:   Error processing docs:  Error: Failed to render - doc "module:material.components.autocomplete.directive:mdAutocomplete" (directive)  - from file "src/components/autocomplete/js/autocompleteDirective.js" - starting at line 5, ending at line 224

Original Error:

Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/lib/macros.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/lib/params.template.html) [Line 12, Column 17]
  Error: Unable to call `paramTable`, which is undefined or falsey
    at Object.exports.prettifyError (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/lib.js:34:15)
    at /Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:486:31
    at new_cls.root [as rootRenderFunc] (<anonymous>:31:3)
    at new_cls.render (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:479:15)
    at /Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:312:35
    at createTemplate (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:234:25)
    at handle (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:249:25)
    at /Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:263:21
    at next (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/lib.js:207:13)
    at Object.exports.asyncIter (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/lib.js:214:5)
    at new_cls.getTemplate (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:242:17)
    at new_cls.render (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:304:14)
    at render (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni-packages/nunjucks/services/nunjucks-template-engine.js:35:23)
    at Object.<anonymous> (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni-packages/base/processors/render-docs.js:50:33)
    at Array.forEach (native)
    at Object.process [as $process] (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni-packages/base/processors/render-docs.js:42:12)
    at /Users/baiyufan/yoApps/lib/material/node_modules/dgeni/lib/Dgeni.js:179:54
    at _fulfilled (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:796:13)
    at /Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:604:44
    at runSingle (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:137:13)
    at flush (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

    at Object.<anonymous> (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni-packages/base/processors/render-docs.js:53:17)
    at Array.forEach (native)
    at Object.process [as $process] (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni-packages/base/processors/render-docs.js:42:12)
    at /Users/baiyufan/yoApps/lib/material/node_modules/dgeni/lib/Dgeni.js:179:54
    at _fulfilled (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:796:13)
    at /Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:604:44
    at runSingle (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:137:13)
    at flush (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

[13:37:46] 'docs-generate' errored after 3.16 s
[13:37:46] Error: Failed to render - doc "module:material.components.autocomplete.directive:mdAutocomplete" (directive)  - from file "src/components/autocomplete/js/autocompleteDirective.js" - starting at line 5, ending at line 224

Original Error:

Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/lib/macros.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/api/directive.template.html)
  Template render error: (/Users/baiyufan/yoApps/lib/material/docs/config/template/ngdoc/lib/params.template.html) [Line 12, Column 17]
  Error: Unable to call `paramTable`, which is undefined or falsey
    at Object.exports.prettifyError (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/lib.js:34:15)
    at /Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:486:31
    at new_cls.root [as rootRenderFunc] (<anonymous>:31:3)
    at new_cls.render (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:479:15)
    at /Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:312:35
    at createTemplate (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:234:25)
    at handle (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:249:25)
    at /Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:263:21
    at next (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/lib.js:207:13)
    at Object.exports.asyncIter (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/lib.js:214:5)
    at new_cls.getTemplate (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:242:17)
    at new_cls.render (/Users/baiyufan/yoApps/lib/material/node_modules/nunjucks/src/environment.js:304:14)
    at render (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni-packages/nunjucks/services/nunjucks-template-engine.js:35:23)
    at Object.<anonymous> (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni-packages/base/processors/render-docs.js:50:33)
    at Array.forEach (native)
    at Object.process [as $process] (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni-packages/base/processors/render-docs.js:42:12)
    at /Users/baiyufan/yoApps/lib/material/node_modules/dgeni/lib/Dgeni.js:179:54
    at _fulfilled (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:796:13)
    at /Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:604:44
    at runSingle (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:137:13)
    at flush (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

    at Object.<anonymous> (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni-packages/base/processors/render-docs.js:53:17)
    at Array.forEach (native)
    at Object.process [as $process] (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni-packages/base/processors/render-docs.js:42:12)
    at /Users/baiyufan/yoApps/lib/material/node_modules/dgeni/lib/Dgeni.js:179:54
    at _fulfilled (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:796:13)
    at /Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:604:44
    at runSingle (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:137:13)
    at flush (/Users/baiyufan/yoApps/lib/material/node_modules/dgeni/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

[13:37:46] Finished 'demos' after 26 s`

**Comment by changingp** [comment]
maybe same question 

`E:\material-1.1.4>gulp docs
[10:31:06] Using gulpfile E:\Pax\Code\JPax\_chm\material-1.1.4\gulpfile.js
[10:31:06] Starting 'build-scss'...
[10:31:06] Building css files...
[10:31:06] Starting 'build-js'...
[10:31:06] building js files...
[10:31:06] Starting 'docs-html2js'...
[10:31:06] Starting 'demos'...
[10:31:07] Finished 'docs-html2js' after 869 ms`

**Comment by changingp** [comment]
I solved this problem by change another pc which system version is win10。
node-sass use vs2013, vs2013 cann't install on win7，so ...

**Comment by ThomasBurleson** [comment]
Will not support local, windows build issues.

**Comment by lokeb** [comment]
It seems this is not a Windows problem. I am facing this on Mac OS Sierra. Any suggestions?
