### ISSUE TITLE
icon: unable to get property 'replace' of undefined or null reference at transformClone

### ISSUE THREAD

**Issue by Splaktar** [angular/material#11543]
## Bug

# CodePen and steps to reproduce the issue:

#### Detailed Reproduction Steps: 
1. Just open https://material.angularjs.org/latest/
1. browse around the demos a little bit
1. many of these will show up

### What is the expected behavior?
No TypeErrors in console.

### What is the current behavior?
Lots of TypeErrors in console. Full stack below.

### What is the use-case or motivation for changing an existing behavior?
Fully supporting IE11.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.5
- AngularJS Material: 1.1.10 and HEAD (1.1.11)
- OS: Windows
- Browsers: IE11
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
```
TypeError: Unable to get property 'replace' of undefined or null reference
   at transformClone (http://localhost:8080/angular-material.min.js:34088:5)
   at getIcon (http://localhost:8080/angular-material.min.js:34019:7)
   at Anonymous function (http://localhost:8080/angular-material.min.js:33536:11)
   at Anonymous function (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular.min.js:94:115)
   at m.prototype.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular.min.js:151:185)
   at m.prototype.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular.min.js:155:33)
   at Anonymous function (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular.min.js:125:47)
   at og (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular.min.js:40:156)
   at d (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular.min.js:40:105)
```
This may be related to https://github.com/angular/material/issues/10621.

**Comment by Splaktar** [comment]
I'm also seeing the following on the [Icons Demo]():
```
TypeError: Unable to get property '0' of undefined or null reference
   at f (https://material.angularjs.org/HEAD/angular-material.min.js:7:302841)
   at Anonymous function (https://material.angularjs.org/HEAD/angular-material.min.js:7:302310)
   at Anonymous function (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular.min.js:140:40)
   at m.prototype.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular.min.js:151:185)
   at m.prototype.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular.min.js:155:33)
   at k (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular.min.js:106:127)
   at w (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular.min.js:111:203)
   at E.onload (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular.min.js:112:125) Possibly unhandled rejection: {"description":"Unable to get property '0' of undefined or null reference","number":-2146823281,"stack":"TypeError: Unable to get property '0' of undefined or null reference"}
```

**Comment by Splaktar** [comment]
Confirmed that the exception in the OP is a regression in 1.1.11 due to https://stackoverflow.com/questions/28129956/get-innerhtml-of-svg-tag-result-in-undefined-in-ie.
