### ISSUE TITLE
$mdToast: Twice call of $mdToast.show raises exception

### ISSUE THREAD

**Issue by mistercz** [angular/material#1216]
I have service for receiving alerts messages and trying to display toasts instead of classic alerts. So service calls the showToast function

```js
 function showToast(msg) {
      var toast = $mdToast.simple()
          .content(msg)
          .action('OK')
          .highlightAction(false)
          .position('left top right');
      $mdToast.show(toast);
    }
```
When service receives second alert too early, the exception TypeError:undefined is not a function is displayed:

```console
TypeError: undefined is not a function
    at Object.onRemove (http://localhost:63342/analytics/app/bower_components/angular-material/angular-material.js:6985:15)
    at Object.InterimElementFactory.self.remove (http://localhost:63342/analytics/app/bower_components/angular-material/angular-material.js:1392:31)
    at Object.cancel (http://localhost:63342/analytics/app/bower_components/angular-material/angular-material.js:1319:42)
    at Object.show (http://localhost:63342/analytics/app/bower_components/angular-material/angular-material.js:1273:19)
    at Object.showInterimElement [as show] (http://localhost:63342/analytics/app/bower_components/angular-material/angular-material.js:1211:38)
    at showToast (http://localhost:63342/analytics/app/modules/shared/alert/alertSvc.js:13:16)
    at Object.alertDanger (http://localhost:63342/analytics/app/modules/shared/alert/alertSvc.js:25:7)
    at http://localhost:63342/analytics/app/modules/features/login/loginCtrl.js:21:22
    at processQueue (http://localhost:63342/analytics/app/bower_components/angular/angular.js:13171:27)
    at http://localhost:63342/analytics/app/bower_components/angular/angular.js:13187:27
```
I'm using bower package:

```json
  "_release": "8aca69b4ce",
  "_resolution": {
    "type": "branch",
    "branch": "master",
    "commit": "8aca69b4ceb48a8a29a71d9dbe83d177a345e674"
  }, 
```
Thank you

**Comment by EladBezalel** [comment]
I'm sorry but this is unreadable! use [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/) for better view and provide a plunker that reproduce the problem, as you wrote you're function it's seems fine..

**Comment by rschmukler** [comment]
As per [this jsfiddle](http://jsfiddle.net/rschmukler/xbwtd3cf/) using $mdToast and clicking multiple times, I am unable to recreate the issue. If you can recreate it, please open a new issue with the jsfiddle.

**Comment by peluprvi** [comment]
I got the same error. It's not a manual trigger (with clicks).

```javascript
app.controller('ToastDemoCtrl', function($mdToast) {

  $mdToast.show(
    $mdToast.simple()
      .content('Simple Toast!')
  );

  $mdToast.show(
    $mdToast.simple()
      .content('Simple Toast 2!')
  );

});
```

The above code produces the following error:


```javascript

TypeError: Cannot read property 'off' of undefined
    at Object.onRemove (angular-material.js:7206)
    at Object.InterimElementFactory.self.remove (angular-material.js:1629)
    at Object.cancel (angular-material.js:1556)
    at Object.show (angular-material.js:1510)
    at Object.showInterimElement [as show] (angular-material.js:1448)
    at Scope.$rootScope.showToast (auth.js:14)
    at Object.<anonymous> (auth.js:23)
    at Object.invoke (angular.js:4185)
    at Object.enforcedReturnValue [as $get] (angular.js:4038)
    at Object.invoke (angular.js:4185)angular.js:11607 (anonymous function)angular.js:8557 $getangular.js:14502 $get.Scope.$applyangular.js:1448 bootstrapApplyangular.js:4185 invokeangular.js:1446 doBootstrapangular.js:1466 bootstrapangular.js:1360 angularInitangular.js:26125 (anonymous function)angular.js:2744 triggerangular.js:3014 eventHandler
```

**Comment by rschmukler** [comment]
After further investigation, I was able to re-create your problem. Thanks for the help!

**Comment by richarddavenport** [comment]
Is there anyway to show multiple toast notifications then?

**Comment by Carrington** [comment]
Also experiencing this error. Is there any way to clear the previous toast away to prevent this exception?

**Comment by peluprvi** [comment]
It's fixed here, using Chrome with angular-material 0.8.3 version.
