### ISSUE TITLE
multiple subheaders sticky-state bug?

### ISSUE THREAD

**Issue by gribnoysup** [angular/material#1757]
If there are more that one sticky subheader on the screen and ng-show applied to them, scrolling causes them to change sticky-state on every scroll event and therefore the one that should be seen just disappears, or another one sticky subheader appears, if ng-show applied to the subheader parent.

![yt8wcu2 1](https://cloud.githubusercontent.com/assets/5036933/6460891/393c48ca-c1ac-11e4-80fb-30ca7d751450.gif)

This could be avoided by using `ng-if` BUT only if `ng-if` applied to the parent, because applying ng-if to the subheader throws an error (maybe this should be submitted as another issue?):

```
TypeError: undefined is not a function
    at getContent (https://rawgit.com/angular/bower-material/master/angular-material.js:8959:40)
    at https://rawgit.com/angular/bower-material/master/angular-material.js:8973:11
    at publicLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:6940:29)
    at postLink (https://rawgit.com/angular/bower-material/master/angular-material.js:8970:9)
    at invokeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:8194:9)
    at nodeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:7706:11)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:7062:13)
    at publicLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:6941:30)
    at $get.boundTranscludeFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:7080:16)
    at controllersBoundTransclude (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:7733:18) <h2 class="md-subheader ng-scope md-default-theme" ng-if="projectsList.length >
```

plunker: http://plnkr.co/edit/Z4kUpVB8O81r1HF1EaBb?p=preview

**Comment by ThomasBurleson** [comment]
Fixed.
