### ISSUE TITLE
md-autocomplete SyntaxError: Invalid regular expression: /^?/: Nothing to repeat

### ISSUE THREAD

**Issue by BenjaminHofstetter** [angular/material#2292]
I have items in my autocomplete array starting with a '?' character. This leas to the following error message:
```
SyntaxError: Invalid regular expression: /^?/: Nothing to repeat
    at new RegExp (native)
    at Object.fn (http://xx/js/angular-material.js:10442:23)
    at m.$get.m.$digest (http://xx/js/angular.min.js:128:172)
   ...
````
I found that the sanitize function does not escape the question mark. I changed 
```javascript 
function sanitize (term) {
      if (!term) return term;
      return term.replace(/[\*\[\]\(\)\{\}\\\^\$]/g, '\\$&');
}
```

to 
```javascript 
function sanitize (term) {
      if (!term) return term;
      return term.replace(/[\?\*\[\]\(\)\{\}\\\^\$]/g, '\\$&');
}
```
and this solved my problem. Or is it even better to escape all these?
```
\\ \^ \$ \* \+ \? \. \( \) \| \{ \} \[ \]
```

**Comment by robertmesserle** [comment]
@BenjaminHofstetter Excellent find, thanks!  Submitted a fix.
