### ISSUE TITLE
md-tooltip: Support hide-* and show-* attributes

### ISSUE THREAD

**Issue by epelc** [angular/material#2386]
I get the following error when hovering over something that has a disabled tooltip which is using one of the hide or show classes. Also please note this error only happens when you hide the tooltip for whatever you are hovering over.

In my case I'm using
```
<md-tooltip hide show-sm>
      <span ng-bind="..."></span>
</md-tooltip>
```

```
"TypeError: Cannot read property 'scrollHeight' of null
    at positionTooltip (http://dev.*******.com/app/vendor.js:30029:65)
    at showTooltip (http://dev.*******.com/app/vendor.js:30003:8)
    at Object.fn (http://dev.*******.com/app/vendor.js:29942:25)
    at n.$get.n.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:123:356)
    at n.$get.n.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:126:293)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:139:3
    at e (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:40:74)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:44:155"
```

Note this just started with `0.9.0-rc1` it worked fine in `0.8.3`

**Comment by lasdjs** [comment]
Hello this issue, appears again in v0.11.1

**Comment by topherfangio** [comment]
@lasdjs Can you please open a new issue with a Codepen that demonstrates it? Here are some links you can use:

*  Angular Material HEAD
 *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
 *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
 *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
 *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
 *  Angular 1.3.19 (or greater)
 *  Angular 1.4.6 (or greater).
