### ISSUE TITLE
Unable to build docs locally

### ISSUE THREAD

**Issue by budhrg** [angular/material#2407]
Hi,

I am following <a href="https://github.com/angular/material/tree/master/docs" target="_blank">this guide</a> and trying to build the docs locally. 
I have checked in to branch pointing to tag `v0.8.3` as `master` branch was missing `bower.json`.
However, I am getting following error in `gulp docs` step.

```
budhram$ gulp docs

Error: Cannot find module 'fork-stream'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/budhram/_work/opensource/angularjs/angular-material/node_modules/gulp-if/node_modules/ternary-stream/index.js:4:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
What could be issue here?

**Comment by david-gang** [comment]
Hi,

It looks that something with the npm install was not ok.
It looks like it fails to use a dependency of gulp-if, which is correctly in the package.json.

> at Object.<anonymous> (/home/budhram/_work/opensource/angularjs/angular-material
/node_modules/gulp-if/node_modules/ternary-stream/index.js:4:18)

I would try to type npm install again and see if something fails.

Anyway this looks like a npm problem rather a missing package in the material build.

**Comment by ThomasBurleson** [comment]
@david-gang - thx for reply and good hint.
@budhrg - Starting 0.9.0-rc1, we no longer use **bower** within the `/angular/material` repository. Now you use only need to use **npm**.

*  npm v2.7.4
*  node v0.12.2
*  gulp v3.8.11

If you use `npm install` from your project directory all the necessary versions of tools **and** angular libraries should be installed.

> Angular libraries are used only for local builds of the Angular Material docs
