### ISSUE TITLE
md-subheader throws JS error

### ISSUE THREAD

**Issue by dohomi** [angular/material#2513]
Hi,
I just tried the ```md-subheader```component and it throws an JS error
``` 
TypeError: el[0].querySelector is not a function
    at getContent 
```
It happens on ```0.9.0-rc2```version and this is the sample markup:
```
<section>
   <md-subheader class="md-primary" ng-if="vm.contacts.length">
             <h3>{{'CHATS' | translate}}</h3>
   </md-subheader>
</section>
```

**Comment by Clan-Utility** [comment]
Same happened here!

with no <section>

    <md-subheader ng-if="!isValid()">
        ...
    </md-subheader>

**Comment by SAnDAnGE** [comment]
same for me with angular 1.4.0 and angular-material 0.10.0:
```
<md-list>
  <md-subheader class="md-primary" ng-repeat-start="(city, cinemas) in cinema.cities"><h2>{{city}}</h2></md-subheader>
  <md-list-item ng-repeat="ci in cinemas">
    ...
  </md-list-item>
  <md-divider ng-repeat-end></md-divider>
</md-list>
```

```stacktrace
TypeError: el[0].querySelector is not a function
    at getContent (http://mycinema/assets/libs/angular-material/angular-material.js:11153:40)
    at http://mycinema/assets/libs/angular-material/angular-material.js:11167:13
    at publicLinkFn (http://mycinema/assets/libs/angular/angular.js:7387:29)
    at postLink (http://mycinema/assets/libs/angular-material/angular-material.js:11165:11)
    at invokeLinkFn (http://mycinema/assets/libs/angular/angular.js:8604:9)
    at nodeLinkFn (http://mycinema/assets/libs/angular/angular.js:8113:11)
    at compositeLinkFn (http://mycinema/assets/libs/angular/angular.js:7514:13)
    at publicLinkFn (http://mycinema/assets/libs/angular/angular.js:7388:30)
    at $get.boundTranscludeFn (http://mycinema/assets/libs/angular/angular.js:7533:16)
    at controllersBoundTransclude (http://mycinema/assets/libs/angular/angular.js:8140:18) <h2 class="md-primary md-subheader ng-scope md-default-theme" ng-repeat="(city, cinemas) in cinema.cities" data-ng-animate="1">
```

**Comment by robertmesserle** [comment]
I'm unable to recreate this issue.  Closing for now.  Please reply with a demo if this is still an issue with the latest code in master.
