### ISSUE TITLE
An empty md-list-item throws an exception

### ISSUE THREAD

**Issue by ddimitrop** [angular/material#2649]
Code like that throws an exception in 0.9

    <md-list>
      <md-list-item>
      </md-list-item>        
    </md-list>

http://codepen.io/anon/pen/jPPLJZ

**Comment by ddimitrop** [comment]
TypeError: Cannot read property 'addEventListener' of null
    at s (https://material.angularjs.org/docs.js:1:19958)
    at Z (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:70:356)
    at J (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:59:484)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:52:9)
    at J (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:59:428)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:52:9)
    at J (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:59:428)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:52:9)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:52:26)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:51:118 <md-list-item role="listitem" class="md-no-proxy">

**Comment by ddimitrop** [comment]
https://github.com/angular/material/blob/master/src/components/list/list.js#L207

**Comment by christianmenz** [comment]
Just had the same issue while trying to add ng-switch on the md-list item. I guess it's the same root cause.

<md-list-item ng-switch="some.attribtute">
  <md-input-container ng-switch-when="a">....</md-input-container>
</md-list-item>

**Comment by Janpot** [comment]
It seems to happen when there's no `ng-click` on the `<md-list-item>`.

**Comment by mertenhanisch** [comment]
+1
Lists should be possible without ng-click

**Comment by r0b-** [comment]
+1

**Comment by schmkr** [comment]
+1

**Comment by nestorneto** [comment]
+1
