### ISSUE TITLE
An md-subheader with ng-if throws an exception

### ISSUE THREAD

**Issue by ddimitrop** [angular/material#2650]
http://codepen.io/anon/pen/aOOyMx

Code:
```html
<md-list>
      <md-subheader ng-if="true" >
        test
      </md-subheader>
</md-list>
```
throws:
```console
TypeError: e[0].querySelector is not a function
    at d (https://material.angularjs.org/docs.js:3:16194)
    at https://material.angularjs.org/docs.js:3:16352
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:51:108
    at MdSubheaderDirective.compile (https://material.angularjs.org/docs.js:3:16300)
    at Z (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:70:356)
    at J (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:59:484)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:52:9)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:51:118
    at $get.l (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:52:497)
    at k (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js:57:62) <h2 class="md-subheader ng-scope md-default-theme" ng-if="true">
```

**Comment by ddimitrop** [comment]
https://github.com/angular/material/blob/977a495e7d3de27bebabdebaaf5611c9d06a1e22/src/components/subheader/subheader.js#L59

**Comment by dmackerman** [comment]
Can confirm this. Was wondering where that error was coming from! :+1:

**Comment by topherfangio** [comment]
Confirmed in latest 0.10.1 release. Will fix.
