### ISSUE TITLE
problems with md-dialog scope

### ISSUE THREAD

**Issue by david-gang** [angular/material#2696]
I have the following plunkr
http://plnkr.co/edit/JEpU7XOyGKeuAkq4HnHK?p=preview

I have a link and when i press on it the following function is called:
```javascript
 this.link1 = function() {
    $mdDialog.show({
			scope:{
			  item: "="
			},
				template:'<md-dialog><md-dialog-content>Hi There {{item}}</md-dialog-content></md-dialog>'
			});
  };
```
When i press on the link i get:
>TypeError: scope.$watch is not a function
    at textInterpolateLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.js:8058:21)
    at invokeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.js:8258:9)
    at nodeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.js:7768:11)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.js:7117:13)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.js:7120:13)
    at nodeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.js:7763:24)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.js:7117:13)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.js:7120:13)
    at publicLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.js:6996:30)
    at Object.link (https://rawgit.com/angular/bower-material/master/angular-material.js:1144:18) hi there {{item}}(anonymous function) @ angular.js:11655(anonymous function) @ angular.js:8596invokeLinkFn @ angular.js:8260nodeLinkFn @ angular.js:7768compositeLinkFn @ angular.js:7117compositeLinkFn @ angular.js:7120nodeLinkFn @ angular.js:7763compositeLinkFn @ angular.js:7117compositeLinkFn @ angular.js:7120publicLinkFn @ angular.js:6996link @ angular-material.js:1144InterimElement.self.show.compilePromise.then.showDone @ angular-material.js:2119processQueue @ angular.js:13248(anonymous function) @ angular.js:13264Scope.$eval @ angular.js:14466Scope.$digest @ angular.js:14282Scope.$apply @ angular.js:14571(anonymous function) @ angular.js:21571jQuery.event.dispatch @ jquery-2.1.4.js:4435elemData.handle @ jquery-2.1.4.js:4121

When i press escape to close the dialog i get:

>angular.js:11655 TypeError: options.scope.$destroy is not a function
    at angular-material.js:5025
    at processQueue (angular.js:13248)
    at angular.js:13264
    at Scope.$eval (angular.js:14466)
    at Scope.$digest (angular.js:14282)
    at angular.js:14505
    at completeOutstandingRequest (angular.js:4924)
    at angular.js:5312

**Comment by ThomasBurleson** [comment]
@david-gang - your Plunkr has several problems.ere is a working version: http://plnkr.co/edit/tJOkZBmMUkPmKOCkj2Wh?p=preview

*  See revision to use of **controller as** syntax
*  See fix to passing locals to dialog instance and its isolated scope
*  See use of dialog controller

**Comment by ThomasBurleson** [comment]
@david-gang - these general "my code does not work" should best be posted in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)... so others can learn also.

**Comment by david-gang** [comment]
Hi @ThomasBurleson,
Please correct me if i am wrong.
I think that here it is a bit different, because in the angular forum i post issues, where i need help how to accomplish something.
If i work according the documentation and get exceptions, this should be an issue.

In the documentation at https://material.angularjs.org/#/api/material.components.dialog/service/$mdDialog it is written explicitly that the scope property can be used:
>scope - {object=}: the scope to link the template / controller to. If none is specified, it will create a new isolate scope. This scope will be destroyed when the dialog is removed unless preserveScope is set to true.

If my distinction is not precise, then please let me know when to post here in this forum. What should be the workflow.

**Comment by ThomasBurleson** [comment]
@david-gang 
You can use this syntax here:

```js
.controller('AppCtrl', function($scope, $mdDialog) {
  this.item= "David Gang";
  this.greeting1 = function() {
    $mdDialog.show({
      clickOutsideToClose : true,
			scope:$scope,         // use parent scope in template
			preserveScope: true,  // do not forget this if use parent scope
			// Since controller is instantiated with controllerAs syntax
			// AND we are passing the parent scope to the dialog, we MUST
			// use `vm.<xxx>` 
			template:'<md-dialog><md-dialog-content>Hi There {{vm.item}}</md-dialog-content></md-dialog>',
      controller: function DialogController($scope, $mdDialog) {
        $scope.closeDialog = function() {
          $mdDialog.hide();
        }
      }
    });      
  };
```

The documentation is **not** clear and I will update the docs. Thank you for persistence in getting these docs improved.

**Comment by ThomasBurleson** [comment]
![screen shot 2015-05-04 at 11 48 42 am](https://cloud.githubusercontent.com/assets/210413/7457616/8675fd5c-f253-11e4-83fc-761a6d7e17ab.png)

**Comment by david-gang** [comment]
Thanks @ThomasBurleson,
Now it is very clean how to use this service.

**Comment by nikkwong** [comment]
Hi, sorry, in the example above what is $scope.vm === <controller instance=""> ..?
