### ISSUE TITLE
autocomplete js error offsetTop undefined v0.9

### ISSUE THREAD

**Issue by CuthbertJungle** [angular/material#2774]
to recreate in the floating label autocomplete codepen example
1) type in "Wisconsin"
2) select result from list
3) hit up or down arrow button

TypeError: Cannot read property 'offsetTop' of undefined
    at updateScroll (http://localhost:3000/bower_components/angular-material/angular-material.js:11166:17)
    at MdAutocompleteCtrl.keydown (http://localhost:3000/bower_components/angular-material/angular-material.js:11046:9)
    at $parseFunctionCall (http://localhost:3000/bower_components/angular/angular.js:12404:18)
    at ngEventDirectives.(anonymous function).compile.element.on.callback (http://localhost:3000/bower_components/angular/angular.js:21566:17)
    at Scope.$get.Scope.$eval (http://localhost:3000/bower_components/angular/angular.js:14466:28)
    at Scope.$get.Scope.$apply (http://localhost:3000/bower_components/angular/angular.js:14565:23)
    at HTMLInputElement.<anonymous> (http://localhost:3000/bower_components/angular/angular.js:21571:23)
    at HTMLInputElement.eventHandler (http://localhost:3000/bower_components/angular/angular.js:3032:21)angular.js:11655 (anonymous function)angular.js:8596 $getangular.js:14567 $get.Scope.$applyangular.js:21571 (anonymous function)angular.js:3032 eventHandler

**Comment by RaphaelYanis** [comment]
I got TypeError: li is undefined.

You also get this error whenever you set the autocomplete md-min-length > 0
