### ISSUE TITLE
bug: md-list-item generates bogus error "cannot read property 'addEventListener' of null"

### ISSUE THREAD

**Issue by HenrikBechmann** [angular/material#2910]
The following error appears with ng-repeat in md-list-item, but not in md-grid-tile, nor in table row

This has no apparent effect on rendering

ngMaterial 0.9.4; same with angular 1.3.15

TypeError: Cannot read property 'addEventListener' of null
    at postLink (http://mustertools/bower_components/angular-material/angular-material.js:6792:21)
    at invokeLinkFn (http://mustertools/angular/angular-1.4.0-rc.2/angular.js:8587:9)
    at nodeLinkFn (http://mustertools/angular/angular-1.4.0-rc.2/angular.js:8096:11)
    at compositeLinkFn (http://mustertools/angular/angular-1.4.0-rc.2/angular.js:7497:13)
    at publicLinkFn (http://mustertools/angular/angular-1.4.0-rc.2/angular.js:7371:30)
    at boundTranscludeFn (http://mustertools/angular/angular-1.4.0-rc.2/angular.js:7516:16)
    at controllersBoundTransclude (http://mustertools/angular/angular-1.4.0-rc.2/angular.js:8123:18)
    at ngRepeatAction (http://mustertools/angular/angular-1.4.0-rc.2/angular.js:26918:15)
    at Object.$watchCollectionAction [as fn] (http://mustertools/angular/angular-1.4.0-rc.2/angular.js:15404:13)
    at Scope.$digest (http://mustertools/angular/angular-1.4.0-rc.2/angular.js:15539:29) <md-list-item ng-repeat="item in get(':items')" ng-switch="item.type" class="md-whiteframe-z2 md-no-proxy ng-scope" role="listitem" data-ng-animate="1">

**Comment by geret13** [comment]
+1

**Comment by HenrikBechmann** [comment]
Yes most likely, feel free to close.

**Comment by topherfangio** [comment]
Closing the issue; if it re-presents itself, please make a comment and we can re-open, or submit a new issue.
