### ISSUE TITLE
md-autocomplete : bug on mouseUp

### ISSUE THREAD

**Issue by jgoux** [angular/material#3203]
Hello,
in the master, there is an error in the console as soon as we select an item in the suggestion list : 
```
ReferenceError: element is not defined
    at e.T [as mouseUp] (https://material.angularjs.org/HEAD/angular-material.min.js:11:22644)
    at ib.functionCall (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:199:303)
    at Ec.(anonymous function).compile.d.on.f (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:216:74)
    at n.$get.n.$eval (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:126:15)
    at n.$get.n.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:126:241)
    at HTMLUListElement.<anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:216:126)
    at HTMLUListElement.c (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:32:389)
```

You can see it here : https://material.angularjs.org/HEAD/#/demo/material.components.autocomplete

**Comment by schmkr** [comment]
Also ran into this issue. I think [here](https://github.com/angular/material/commit/d3f6519561d638b16a7c31e1b53a3babce0f5082#diff-9fc89ffc72f2f7401be3ee31862a8476R218)

```
function onMouseup () {
    element.input.focus();
}
```
`elements` should be instead of `element`.

**Comment by Izcalli** [comment]
+1

**Comment by Sriram143** [comment]
changing element to elements is fixed this issue.
+1

**Comment by heavysixer** [comment]
+1
