### ISSUE TITLE
md-tooltip error with dynamic text (0.9.8)

### ISSUE THREAD

**Issue by nestorneto** [angular/material#3230]
I tried to make a dynamic tooltip text, it works with console errors.. 

```html
<md-tooltip>
     <span ng-bind="tooltipText()"></span>
</md-tooltip>
```

Errors:

```javascript
TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at TypeError (native)
    at getParentWithPointerEvents (http://localhost/main/vendor/angular-material/angular-material.js:11134:32)
    at postLink (http://localhost/main/vendor/angular-material/angular-material.js:11087:25)
    at http://localhost/main/vendor/angular/angular.js:8598:44
    at invokeLinkFn (http://localhost/main/vendor/angular/angular.js:8604:9)
    at nodeLinkFn (http://localhost/main/vendor/angular/angular.js:8113:11)
    at compositeLinkFn (http://localhost/main/vendor/angular/angular.js:7514:13)
    at publicLinkFn (http://localhost/main/vendor/angular/angular.js:7388:30)
    at $get.boundTranscludeFn (http://localhost/main/vendor/angular/angular.js:7533:16)
    at controllersBoundTransclude (http://localhost/main/vendor/angular/angular.js:8140:18) <md-tooltip class="ng-scope ng-isolate-scope md-default-theme">(anonymous function) @ angular.js:12221$get @ angular.js:9055invokeLinkFn @ angular.js:8606nodeLinkFn @ angular.js:8113compositeLinkFn @ angular.js:7514publicLinkFn @ angular.js:7388$get.boundTranscludeFn @ angular.js:7533controllersBoundTransclude @ angular.js:8140postLink @ acl-for-action.js:59(anonymous function) @ angular.js:8598invokeLinkFn @ angular.js:8604nodeLinkFn @ angular.js:8113compositeLinkFn @ angular.js:7514compositeLinkFn @ angular.js:7518publicLinkFn @ angular.js:7388$get.boundTranscludeFn @ angular.js:7533controllersBoundTransclude @ angular.js:8140ngIfWatchAction @ angular.js:23603$get.Scope.$digest @ angular.js:15556$get.Scope.$apply @ angular.js:15824done @ angular.js:10263completeRequest @ angular.js:10435requestLoaded @ angular.js:10376
```

I'm doing anything wrong?

**Comment by marcysutton** [comment]
Can you try binding the text another way and see if the error still throws?
```
<md-tooltip>
     <span>{{ tooltipText() }}</span>
</md-tooltip>
```
Also, what is wrapping the tooltip? That could be the `aria-label` utility looking for actual text to label the parent for assistive technologies.

**Comment by nestorneto** [comment]
Yes, it throws errors even binding in that way.

this tooltip is for a md-button.

**Comment by marcysutton** [comment]
@nestorneto ok, can you post your whole `md-button` code, either in a Plunker or a Codepen? It will help to debug. I'm still guessing the text isn't available in time to provide an accessible name to the parent button.

**Comment by nestorneto** [comment]
Sorry, I'm trying to replicate the errors in codepen but I'm not getting it. Then, I realized that another custom directive in md-button is causing the errors.

I will continue to investigate, but apparently it's our mistake.

**Comment by topherfangio** [comment]
@nestorneto Please comment if you're still having trouble and we can re-open; but since you said it's on your end, I am going to go ahead and close this.
