### ISSUE TITLE
<md-tabs > does not work

### ISSUE THREAD

**Issue by lakakenny** [angular/material#3719]
Error: [$parse:syntax] Syntax Error: Token ')' is an unexpected token at column 19 of the expression [$mdTabsCtrl.select)] starting at [)].
http://errors.angularjs.org/1.3.15/$parse/syntax?p0=)&p1=is%20an%20unexpected%20token&p2=19&p3=%24mdTabsCtrl.select)&p4=)
    at http://localhost:9000/bower_components/angular/angular.js:63:12
    at Parser.throwError (http://localhost:9000/bower_components/angular/angular.js:12070:11)
    at Parser.parse (http://localhost:9000/bower_components/angular/angular.js:12023:12)
    at $parse (http://localhost:9000/bower_components/angular/angular.js:12737:39)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1707:17
    at Array.forEach (native)
    at ngEventHandler (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1702:20)
    at invokeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8258:9)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7768:11)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7117:13) <md-tab-item tabindex="-1" class="md-tab ng-scope ng-isolate-scope" style="max-width: {{ tabWidth ? tabWidth + 'px' : 'none' }}" ng-repeat="tab in $mdTabsCtrl.tabs" role="tab" aria-controls="tab-content-{{tab.id}}" aria-selected="{{tab.isActive()}}" aria-disabled="{{tab.scope.disabled || 'false'}}" ng-click="$mdTabsCtrl.select(tab.getIndex())" ng-class="{                      'md-active':    tab.isActive(),                      'md-focused':   tab.hasFocus(),                      'md-disabled':  tab.scope.disabled                  }" ng-disabled="tab.scope.disabled" md-swipe-left="$mdTabsCtrl.nextPage()" md-swipe-right="$mdTabsCtrl.previousPage()" md-template="tab.label" md-scope="tab.parent">

**Comment by giomv** [comment]
I'm also experiencing this issue, just on Chrome. On Firefox is working correctly.

**Comment by giomv** [comment]
I'm also experiencing this issue, just on Chrome. On Firefox is working correcty.

**Comment by dbranizor** [comment]
I have the same issue. Everything worked up until this week. Have a setup where I am using multiple controllers with each controller assigned to the individual tab.

**Comment by al081570** [comment]
I've already found this issue. On Firefox also works for me.

**Comment by thegreycell** [comment]
Try clearing your cookies. It seems that triangular stores some information in a cookie that it reuses upon a revisit. The same will work without any issues in a Firefox browser

On 15-Jul-2015 2:52 pm, dbranizor <notifications@github.com> wrote:
I have the same issue. Everything worked up until this week. Have a setup where I am using multiple controllers with each controller assigned to the individual tab.

---

**Comment by al081570** [comment]
Nice!! It worked for me!!

**Comment by lakakenny** [comment]
Hello ,
Thanks, I have solved my issue. I have removed the batarang chrome
extensions

**Comment by giomv** [comment]
Thanks! It was a matter of erasing cookies for me too.

**Comment by trngle** [comment]
Clearing cookies worked for me as well.
Do we know why though?

**Comment by JulioGold** [comment]
I disabled the batarang and it solve the problem.
After I uninstalled the Batarang and installed ng-inspector that is much better.

**Comment by PseudoSky** [comment]
I also had batarang and had to remove the _debug cookie to get things working.

**Comment by amritk** [comment]
Yep happened after installing batarang, removed and it works! Thanks

**Comment by mattspaulding** [comment]
Get rid of Batarang

**Comment by Chidan** [comment]
thanks guys, diabling batrang helped :+1:
