### ISSUE TITLE
How do I set the angular-material with angularAMD ?

### ISSUE THREAD

**Issue by alannsiqueira** [angular/material#3831]
By accessing the index.html I can find all the JS however get the error

Uncaught TypeError: Cannot read property 'module' of undefined
angular.js:4385 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module ngMaterial due to:
Error: [$injector:nomod] Module 'ngMaterial' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.3/$injector/nomod?p0=ngMaterial
    at http://localhost:63342/meuTeste/www/lib/angular/angular.js:68:12
    at http://localhost:63342/meuTeste/www/lib/angular/angular.js:1958:17
    at ensure (http://localhost:63342/meuTeste/www/lib/angular/angular.js:1882:38)
    at module (http://localhost:63342/meuTeste/www/lib/angular/angular.js:1956:14)
    at http://localhost:63342/meuTeste/www/lib/angular/angular.js:4362:22
    at forEach (http://localhost:63342/meuTeste/www/lib/angular/angular.js:336:20)
    at loadModules (http://localhost:63342/meuTeste/www/lib/angular/angular.js:4346:5)
    at http://localhost:63342/meuTeste/www/lib/angular/angular.js:4363:40
    at forEach (http://localhost:63342/meuTeste/www/lib/angular/angular.js:336:20)
    at loadModules (http://localhost:63342/meuTeste/www/lib/angular/angular.js:4346:5)
http://errors.angularjs.org/1.4.3/$injector/modulerr?p0=ngMaterial&p1=Error…localhost%3A63342%2FmeuTeste%2Fwww%2Flib%2Fangular%2Fangular.js%3A4346%3A5)
    at http://localhost:63342/meuTeste/www/lib/angular/angular.js:68:12
    at http://localhost:63342/meuTeste/www/lib/angular/angular.js:4385:15
    at forEach (http://localhost:63342/meuTeste/www/lib/angular/angular.js:336:20)
    at loadModules (http://localhost:63342/meuTeste/www/lib/angular/angular.js:4346:5)
    at http://localhost:63342/meuTeste/www/lib/angular/angular.js:4363:40
    at forEach (http://localhost:63342/meuTeste/www/lib/angular/angular.js:336:20)
    at loadModules (http://localhost:63342/meuTeste/www/lib/angular/angular.js:4346:5)
    at createInjector (http://localhost:63342/meuTeste/www/lib/angular/angular.js:4272:11)
    at doBootstrap (http://localhost:63342/meuTeste/www/lib/angular/angular.js:1630:20)
    at Object.bootstrap (http://localhost:63342/meuTeste/www/lib/angular/angular.js:1651:12)
http://errors.angularjs.org/1.4.3/$injector/modulerr?p0=app&p1=Error%3A%20%…ocalhost%3A63342%2FmeuTeste%2Fwww%2Flib%2Fangular%2Fangular.js%3A1651%3A12)

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
