### ISSUE TITLE
gulp command to create documentation runs but still have errors viewing the docs...

### ISSUE THREAD

**Issue by jeffthompson1971** [angular/material#425]
Per the read-me:
    "gulp docs" to build docs into dist/docs

the task runs successfully and writes everything to dist/docs, but it's not actually usable.  I get the following error trying to view the docs:

 Uncaught Error: [$injector:modulerr] Failed to instantiate module docsApp due to:
Error: [$injector:modulerr] Failed to instantiate module angularytics due to:
Error: [$injector:nomod] Module 'angularytics' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.0-rc.4/$injector/nomod?p0=angularytics
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:80:12
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:1787:17
    at ensure (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:1711:38)
    at module (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:1785:14)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:4024:22
    at forEach (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:330:20)
    at loadModules (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:4008:5)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:4025:40
    at forEach (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:330:20)
    at loadModules (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:4008:5)
http://errors.angularjs.org/1.3.0-rc.4/$injector/modulerr?p0=angularytics&p…gleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.0-rc.4%2Fangular.js%3A4008%3A5)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:80:12
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:4047:15
    at forEach (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:330:20)
    at loadModules (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:4008:5)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:4025:40
    at forEach (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:330:20)
    at loadModules (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:4008:5)
    at createInjector (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:3948:11)
    at doBootstrap (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:1480:20)
    at bootstrap (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.4/angular.js:1501:12)
http://errors.angularjs.org/1.3.0-rc.4/$injector/modulerr?p0=docsApp&p1=Err…leapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.0-rc.4%2Fangular.js%3A1501%3A12)

**Comment by hasangilak** [comment]
for any one encountering this issue 
before doing any gulp things . do bower install in root (where bower.json exists) 
then go for gulp build and then gulp docs .

**Comment by riapp** [comment]
Got same issue. Fixed by running:
1) bower update
2) gulp build
3) gulp docs
 
Thank you guys.

**Comment by alirezamirian** [comment]
but there is no bower.json in the root!
