### ISSUE TITLE
wrong selected user in demo site of radio button, section: ''multi-column

### ISSUE THREAD

**Issue by tenshiAMD** [angular/material#5623]
This happens in the 3rd and 4th row... the selected user remains "Castel"... expected 3rd row selected user is "Cervantes". 

https://material.angularjs.org/latest/demo/radioButton

**Comment by aavielmd** [comment]
ping

**Comment by InsidersByte** [comment]
All the rows select the wrong values. This is because the user is selected by ids and the ids start at 1 instead of zero.

```
self.contacts = [{
      'id': 1,
      'fullName': 'Maria Guadalupe',
      'lastName': 'Guadalupe',
      'title': "CEO, Found"
    },
    ....
```

```
self.selectedUser = function() {
      return self.contacts[self.selectedIndex].lastName;
    }
```

the id is used to set the selected index.

**Comment by tenshiAMD** [comment]
The error changed in RC7. This error appeared when clicking the last user in the demo website.

TypeError: Cannot read property 'lastName' of undefined
    at self.selectedUser (https://material.angularjs.org/latest/docs-demo-scripts.js:1703:47)
    at fn (eval at <anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js:213:110), <anonymous>:4:239)
    at Object.get (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js:114:421)
    at r.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js:131:14)
    at r.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js:134:78)
    at HTMLElement.s (https://material.angularjs.org/latest/angular-material.min.js:10:27362)
    at If (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js:35:367)
    at HTMLElement.Hf.d (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js:35:314)
