### ISSUE TITLE
gulp fails on latest build

### ISSUE THREAD

**Issue by jpike88** [angular/material#6110]
I do npm install, when I try to use gulp I get this error:

Me-Computer:material-master me$ gulp
/Users/me/Downloads/material-master/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:46
});
   
SyntaxError: Unexpected end of input
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/me/Downloads/material-master/node_modules/gulp/node_modules/orchestrator/index.js:8:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
Joshs-Mac-mini:material-master me $ gulp build
/Users/me/Downloads/material-master/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:46
});
   
SyntaxError: Unexpected end of input
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/me/Downloads/material-master/node_modules/gulp/node_modules/orchestrator/index.js:8:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
Joshs-Mac-mini:material-master me $

**Comment by ThomasBurleson** [comment]
Please manually remove the `node_modules` folder. The build now uses Node v5.x with NPM 3.3.x... please update those tools. Then try:

`npm install`

> This should resolve your issues.  I will close this issue; but will reopen if you problem(s) persist.
