### ISSUE TITLE
Release script doesn't work with node 4.X

### ISSUE THREAD

**Issue by jelbourn** [angular/material#6392]
```
undefined:1
TypeError: child_process.execSync(...).trim is not a function
^

SyntaxError: Unexpected token T
    at Object.parse (native)
    at /usr/local/google/home/jelbourn/ng-material/release.js:17:29
    at Object.<anonymous> (/usr/local/google/home/jelbourn/ng-material/release.js:420:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

```

**Comment by ThomasBurleson** [comment]
No longer an issue.
