### ISSUE TITLE
Uncaught Error: ngMaterial requires HammerJS to be preloaded.

### ISSUE THREAD

**Issue by sysmat007** [angular/material#669]
stack:
Uncaught Error: ngMaterial requires HammerJS to be preloaded. (15:46:39:013 | error, javascript)
    at validateEnvironment (app/bower_components/angular-material/angular-material.js:19:15)
    at invoke (app/bower_components/angular/angular.js:4118:17)
    at (anonymous function) (app/bower_components/angular/angular.js:3940:71)
    at forEach (app/bower_components/angular/angular.js:339:20)
    at createInjector (app/bower_components/angular/angular.js:3940:3)
    at doBootstrap (app/bower_components/angular/angular.js:1451:20)
    at bootstrap (app/bower_components/angular/angular.js:1472:12)
    at angularInit (app/bower_components/angular/angular.js:1366:5)
    at (anonymous function) (app/bower_components/angular/angular.js:25717:5)
    at trigger (app/bower_components/angular/angular.js:2709:7)
    at eventHandler (app/bower_components/angular/angular.js:2979:21)

bower.json:
{
  "name": "angular-seed",
  "description": "A starter project for AngularJS",
  "version": "0.0.0",
  "homepage": "https://github.com/angular/angular-seed",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "angular": "1.3.x",
    "angular-route": "1.3.x",
    "angular-loader": "1.3.x",
    "angular-mocks": "~1.3.x",
    "bootstrap": "~3.2.0",
    "angular-animate": "1.2.0",
    "angular-material": "~0.5.x",  
    "html5-boilerplate": "~4.3.0"
  }
}

**Comment by lee-40square** [comment]
@jelbourn Unless I'm missing something shouldn't the documentation specifically mention that Angular Material requires HammerJS?

**Comment by jelbourn** [comment]
@lee-40square The dependency on hammer was removed in 0.7.

**Comment by Marabyte** [comment]
I'm using angular material 0.7.1 and also seeing the same issue.

**Comment by jelbourn** [comment]
Here's the commit where Hammer dependency was removed in December: https://github.com/jelbourn/material/commit/8364fb57a9ac1b211c09ff564fea6ad0dea94e61#diff-dfe07c186488ee794e2200e24b2bd54aL13

It was actually 0.7.1, not 0.7.0, but it should definitely be gone.
