### ISSUE TITLE
TypeError: Cannot read property 'focus' of undefined in MdTabsController.redirectFocus

### ISSUE THREAD

**Issue by craigsh** [angular/material#6776]
I'm having some focus issues with my application, but when it does go wrong, I get this:

TypeError: Cannot read property 'focus' of undefined
    at MdTabsController.redirectFocus (http://localhost:3000/jspm_packages/github/angular/bower-material@1.0.2/angular-material.js:23818:45)
    at fn (eval at <anonymous> (unknown source), <anonymous>:4:295)
    at callback (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0-rc.0/angular.js:24278:17)
    at Scope.$eval (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0-rc.0/angular.js:16554:28)
    at Scope.$apply (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0-rc.0/angular.js:16654:25)
    at HTMLElement.<anonymous> (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0-rc.0/angular.js:24283:23)
    at defaultHandlerWrapper (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0-rc.0/angular.js:3471:11)
    at HTMLElement.eventHandler (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0-rc.0/angular.js:3459:9)

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/pen?template=bEGJdd
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by CxRes** [comment]
I have also had the exact same error when I upgraded angular to 1.5.4. It does not happen in angular 1.5.3. Unfortunately I cannot replicate it on the Codepen and do not understand why it occurs...

**Comment by ThomasBurleson** [comment]
This is a known issue with the Angular 1.5.4 release and the [**$compile change**](https://github.com/angular/angular.js/commit/21d148aedc29c7efba4131ff2ef6383b4700868c) in that release is being rolled back.
