### ISSUE TITLE
angular-material.js doesn't work with JSMIN

### ISSUE THREAD

**Issue by bobber205** [angular/material#6985]
We just JSMIN to compile our js assets/templates as part of our deploy process.

Angular-material.js causes the following error:

```
rake aborted!
JSMin parse error: unterminated string literal:
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jsmin-1.0.1/lib/jsmin.rb:158:in `block in action_copy'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jsmin-1.0.1/lib/jsmin.rb:143:in `loop'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jsmin-1.0.1/lib/jsmin.rb:143:in `action_copy'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jsmin-1.0.1/lib/jsmin.rb:88:in `minify'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jammit-0.7.0/lib/jammit/jsmin_compressor.rb:8:in `compress'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jammit-0.7.0/lib/jammit/compressor.rb:87:in `compress_js'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jammit-0.7.0/lib/jammit/packager.rb:84:in `pack_javascripts'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jammit-0.7.0/lib/jammit/packager.rb:36:in `block in precache_all'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jammit-0.7.0/lib/jammit/packager.rb:36:in `each'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jammit-0.7.0/lib/jammit/packager.rb:36:in `precache_all'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jammit-0.7.0/lib/jammit.rb:146:in `package!'
/opt/frontend/Rakefile:119:in `block in <top (required)>'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/ubuntu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/ubuntu/.rbenv/versions/2.1.2/bin/rake:23:in `load'
/home/ubuntu/.rbenv/versions/2.1.2/bin/rake:23:in `<main>'
```

angular-material.min.js works fine but I'm curious what's up with the non minified version that's invalid?
What do you guys use to minify?

I tend to when possible include non minified versions of files in our  `assets.yml` file to make sure all our JS code is minified with the same minifier.

**Comment by ThomasBurleson** [comment]
will not fix.
