### ISSUE TITLE
error in docs/gulpfile.js

### ISSUE THREAD

**Issue by jaichandra** [angular/material#7362]
When i try to run `gulp docs` or 'npm run watch' on latest master, i get below error.

==========
/AngularLibrary/docs/gulpfile.js:32
          delete file.contents;
                 ^

TypeError: Cannot convert undefined or null to object
    at /AngularLibrary/docs/gulpfile.js:32:18
    at Array.forEach (native)
    at DestroyableTransform._transform (/AngularLibrary/docs/gulpfile.js:31:10)
    at DestroyableTransform.Transform._read (/AngularLibrary/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/AngularLibrary/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/AngularLibrary/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/AngularLibrary/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/AngularLibrary/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/AngularLibrary/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/AngularLibrary/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/AngularLibrary/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:80:13)
    at DestroyableTransform.emit (events.js:179:7)
    at emitReadable_ (/AngularLibrary/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/AngularLibrary/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/AngularLibrary/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
