### ISSUE TITLE
Issue with weird media selector in built CSS

### ISSUE THREAD

**Issue by vyrak** [angular/material#7602]
Hi. I'm having issues loading the distributed css file in a rails app. It's having trouble parsing [this line](https://github.com/angular/bower-material/blob/052cd52/angular-material.css#L24169) when precompiling the assets.

I'm using `sass (3.4.21)`, `sass-rails (5.0.4)`, & `rails (4.2.3)`

I'll understand if this is outside the scope of angular-material, but I'm just curious why the media query is including the `\0` & a new line between `screen` & `and`.

**Comment by crisbeto** [comment]
I believe that's a [CSS hack](http://www.paulirish.com/2009/browser-specific-css-hacks/) to target specific versions of IE.

**Comment by topherfangio** [comment]
I remember this coming up recently in a discussion. Trying to track down the people involved to see what the conclusion was and if this is something we were already planning to fix.

Please ping me if I haven't responded in a day or two.

**Comment by topherfangio** [comment]
Okay, so after discussion, this WAS in our SCSS which was causing problems, so we moved it to be place in just the CSS so that SASS wouldn't try to compile it.

@vyrak Is it actually SASS that is failing? And if so, why is it running plain .CSS through SASS?

**Comment by vyrak** [comment]
When I initially filed this, I was looking at the errors when using the minified CSS file. I'm not sure why it would run it through the sass parser, I'm still investigating that.

```
Sass::SyntaxError: Invalid CSS after "...a screen\0 and ": expected "{", was "(max-width:599p..."
(sass):7
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:1179:in `expected'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:1115:in `expected'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:1110:in `tok!'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:654:in `block'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:407:in `media_directive'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:220:in `special_directive'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:195:in `directive'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:673:in `block_child'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:666:in `block_contents'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:123:in `stylesheet'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:39:in `parse'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/engine.rb:403:in `_to_tree'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/engine.rb:278:in `render'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/sass_compressor.rb:48:in `call'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/sass_compressor.rb:28:in `call'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/loader.rb:60:in `block in load'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/loader.rb:44:in `load'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/cached_environment.rb:47:in `load'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/base.rb:66:in `find_asset'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/manifest.rb:138:in `block in find'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:225:in `block in stat_tree'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:209:in `block in stat_directory'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:206:in `each'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:206:in `stat_directory'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:224:in `stat_tree'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:209:in `block in stat_directory'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:206:in `each'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:206:in `stat_directory'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:224:in `stat_tree'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/legacy.rb:105:in `each'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/legacy.rb:104:in `each'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/legacy.rb:104:in `logical_paths'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/manifest.rb:136:in `find'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/manifest.rb:162:in `compile'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

I also tried the unminified CSS & SCSS files. Oddly enough, they both produced the same error.

```
Sass::SyntaxError: Invalid CSS after "and ": expected "{", was "(max-width: 599..."
(sass):24132
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:1179:in `expected'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:1115:in `expected'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:1110:in `tok!'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:654:in `block'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:407:in `media_directive'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:220:in `special_directive'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:195:in `directive'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:673:in `block_child'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:666:in `block_contents'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:123:in `stylesheet'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/scss/parser.rb:39:in `parse'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/engine.rb:403:in `_to_tree'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sass-3.4.21/lib/sass/engine.rb:278:in `render'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/sass_compressor.rb:48:in `call'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/sass_compressor.rb:28:in `call'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/loader.rb:60:in `block in load'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/loader.rb:44:in `load'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/cached_environment.rb:47:in `load'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/base.rb:66:in `find_asset'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/manifest.rb:138:in `block in find'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:225:in `block in stat_tree'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:209:in `block in stat_directory'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:206:in `each'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:206:in `stat_directory'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:224:in `stat_tree'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:209:in `block in stat_directory'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:206:in `each'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:206:in `stat_directory'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb:224:in `stat_tree'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/legacy.rb:105:in `each'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/legacy.rb:104:in `each'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/legacy.rb:104:in `logical_paths'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/manifest.rb:136:in `find'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/sprockets/manifest.rb:162:in `compile'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-3.4.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/pipeline/source/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

**Comment by topherfangio** [comment]
Can you see if there is perhaps a difference between running it through ruby-sass verses node-sass?

**Comment by ThomasBurleson** [comment]
We will not be supporting this further. Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by avel** [comment]
I believe this is duplicate of #6304
