### ISSUE TITLE
$mdThemingProvider is not defined..

### ISSUE THREAD

**Issue by amanuel2** [angular/material#8107]
```
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module ForumApp due to:
TypeError: Cannot read property 'theme' of undefined
    at stateParams (https://preview.c9users.io/amanuel2/fourm2/router/mainRouter.js:7:19)
    at Object.invoke (https://preview.c9users.io/amanuel2/fourm2/bower_components/angular/angular.js:4625:19)
    at runInvokeQueue (https://preview.c9users.io/amanuel2/fourm2/bower_components/angular/angular.js:4518:35)
    at https://preview.c9users.io/amanuel2/fourm2/bower_components/angular/angular.js:4527:11
    at forEach (https://preview.c9users.io/amanuel2/fourm2/bower_components/angular/angular.js:321:20)
    at loadModules (https://preview.c9users.io/amanuel2/fourm2/bower_components/angular/angular.js:4508:5)
    at createInjector (https://preview.c9users.io/amanuel2/fourm2/bower_components/angular/angular.js:4430:19)
    at doBootstrap (https://preview.c9users.io/amanuel2/fourm2/bower_components/angular/angular.js:1710:20)
    at bootstrap (https://preview.c9users.io/amanuel2/fourm2/bower_components/angular/angular.js:1731:12)
    at angularInit (https://preview.c9users.io/amanuel2/fourm2/bower_components/angular/angular.js:1616:5)
http://errors.angularjs.org/1.5.3/$injector/modulerr?p0=ForumApp&p1=TypeErr…o%2Famanuel2%2Ffourm2%2Fbower_components%2Fangular%2Fangular.js%3A1616%3A5)
```

I dont know why its giving me this... i am using updated version(1.0.7).... 

Here is where im working at:
https://ide.c9.io/amanuel2/fourm2

Please help! Thankyou!

**Comment by DevVersion** [comment]
@amanuel2 Can you please share your code? 

Currently your *demo* requires a third party login, and that's not preferable.

At first look, it looks like it doesn't relate to `ngMaterial`

**Comment by amanuel2** [comment]
@DevVersion ok. 

Index.html:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>Unique Coders</title>
  
  <!-- Javascript Libraries -->
  <script type="text/javascript" src="bower_components/jquery/dist/jquery.js"></script>
  <script type="text/javascript" src="bower_components/angular/angular.js"></script>
  <script type="text/javascript" src="bower_components/angular-ui-router/release/angular-ui-router.js"></script>
  <script type="text/javascript" src="bower_components/angular-material/angular-material.js"></script>
  <script type="text/javascript" src="bower_components/angular-animate/angular-animate.js"></script>
  <script type="text/javascript" src="bower_components/angular-aria/angular-aria.js"></script>
  <script type="text/javascript" src="bower_components/angular-messages/angular-messages.js"></script>
  <script type="text/javascript" src="bower_components/firebase/firebase.js"></script>
  <script type="text/javascript" src="bower_components/angularfire/dist/angularfire.js"></script>
  <script type="text/javascript" src="bower_components/Materialize/dist/js/materialize.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/angular-material-icons/0.7.0/angular-material-icons.min.js"></script>
  <script type="text/javascript" src="lib/svg-assets-cache/svg-assets-cache.js"></script>
  <script type="text/javascript" src="views/assets/css/icons/libs/angular-material-icons.min.js"></script>
  <script type="text/javascript" src="node_modules/alertifyjs/build/alertify.js"></script>
  <script type="text/javascript" src="bower_components/jsSHA/src/sha512.js"></script>
  <script type='text/javascript' src="bower_components/angularjs-crypto/public/js/lib/plugins/CryptoJSCipher.js"></script>
  <script type='text/javascript' src="bower_components/cryptojslib/rollups/aes.js"></script>
  <script type='text/javascript' src="bower_components/angularjs-crypto/public/js/lib/plugins/CryptoJSCipher.js"></script>
  <script type='text/javascript' src="bower_components/angularjs-crypto/public/js/lib/angularjs-crypto.js"></script>
  <script type='text/javascript' src="https://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/aes.js"></script>
  <script type='text/javascript' src="https://crypto-js.googlecode.com/svn/tags/3.1.2/build/components/mode-ecb.js"></script>
  <script type='text/javascript' src="bower_components/angular-cryptography/mdo-angular-cryptography.js"></script>
  <script type="text/javascript" src="https://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/md5.js"></script>
  <script type="text/javascript" src="https://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/hmac-md5.js"></script>
 <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-animate.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-aria.min.js"></script>
  <!-- Styles -->
  <link rel="stylesheet" href="bower_components/angular-material/angular-material.css"/>
  <link rel="stylesheet" href="node_modules/alertifyjs/build/css/alertify.css" />
  <link rel="stylesheet" href="node_modules/alertifyjs/build/css/themes/default.min.css" />
  <link rel="icon shortcut" href="views/assets/images/favicon.ico">
  
  <!-- Controllers, Services, And App -->
  <script type="text/javascript" src="script.js"></script>
  <script type="text/javascript" src="run/authCheck.js"></script>
  <script type="text/javascript" src="router/mainRouter.js"></script>
  <script type="text/javascript" src="services/refService.js"></script>
  <script type="text/javascript" src="services/timeService.js"></script>
  <script type="text/javascript" src="services/dateService.js"></script>
  <script type="text/javascript" src="services/hashService.js"></script>
  <script type="text/javascript" src="services/authCheckTrue.js"></script>
  <script type="text/javascript" src="services/replyService.js"></script>
  <script type="text/javascript" src="directives/userCardDirective.js"></script>
  <script type="text/javascript" src="directives/replyDateDirective.js"></script>
  <script type="text/javascript" src="filters/dateFilter.js"></script>
  <script type="text/javascript" src="controllers/homeCtrl.js"></script>
  <script type="text/javascript" src="controllers/newTopicCtrl.js"></script>
  <script type="text/javascript" src="controllers/newReplyCtrl.js"></script>
  <script type="text/javascript" src="controllers/authDescCtrl.js"></script>
  <script type="text/javascript" src="controllers/topicCtrl.js"></script>
  <script type="text/javascript" src="controllers/loginCtrl.js"></script>
  <script type="text/javascript" src="controllers/authHomeCtrl.js"></script>
  <script type="text/javascript" src="controllers/registerCtrl.js"></script>
  <script type="text/javascript" src="controllers/topicCtrl.js"></script>
  <script type="text/javascript" src="controllers/profileCtrl.js"></script>
</head>
<body ng-app="ForumApp">
	<div id="page">
		<div ui-view>
			
		</div>
	</div>
</body>
</html>

```

mainRouter.js:
```
(function(angular) {
  var app = angular.module('ForumApp');
  app.config(['$stateProvider', '$urlRouterProvider', stateParams])

  function stateParams($stateProvider, $urlRouterProvider, $mdIconProvider,$mdThemingProvider) {

$mdThemingProvider.theme('forest')
      .primaryPalette('brown')
      .accentPalette('green');
      
      
    $urlRouterProvider.otherwise('home')
    $stateProvider.state('home', {
      url: '/home',
      templateUrl: 'views/home.html',
      controller: 'homeCtrl',
    })
    $stateProvider.state('login', {
      url: '/login',
      templateUrl: 'views/login.html',
      controller: 'loginCtrl',
    })
    $stateProvider.state('register', {
      url: '/register',
      templateUrl: 'views/register.html',
      controller: 'registerCtrl',
    })

    $stateProvider.state('authHome', {
      url: '/authHome',
      templateUrl: 'views/authHome.html',
      controller: 'authHome',
      resolve: {
        // controller will not be loaded until $waitForAuth resolves
        // Auth refers to our $firebaseAuth wrapper in the example above
        "currentAuth": ["refService", function(refService) {
          // $waitForAuth returns a promise so the resolve waits for it to complete
          return refService.refAuth().$requireAuth();
        }]
      }
    })

    $stateProvider.state('authHome.desc', {
      url: '/desc',
      templateUrl: 'views/authDesc.html',
      controller: 'authDescCtrl',
      resolve: {
        // controller will not be loaded until $waitForAuth resolves
        // Auth refers to our $firebaseAuth wrapper in the example above
        "currentAuth": ["refService", function(refService) {
          // $waitForAuth returns a promise so the resolve waits for it to complete
          return refService.refAuth().$requireAuth();
        }]
      }
    })

    $stateProvider.state('authHome.topic', {
      url: '/topic?AVATAR?DATE?EMAIL?TITLE?UID?USERNAME?VALUE?',
      templateUrl: 'views/topicDesc.html',
      controller: 'topicCtrl',
      resolve: {
        // controller will not be loaded until $waitForAuth resolves
        // Auth refers to our $firebaseAuth wrapper in the example above
        "currentAuth": ["refService", function(refService) {
          // $waitForAuth returns a promise so the resolve waits for it to complete
          return refService.refAuth().$requireAuth();
        }]
      }
    })
    $stateProvider.state('authHome.profile', {
      url: '/profile:UID',
      templateUrl: 'views/profile.html',
      controller: 'profileCtrl',
      resolve: {
        // controller will not be loaded until $waitForAuth resolves
        // Auth refers to our $firebaseAuth wrapper in the example above
        "currentAuth": ["refService", function(refService) {
          // $waitForAuth returns a promise so the resolve waits for it to complete
          return refService.refAuth().$requireAuth();
        }]
      }
    })

  }
})(angular);
```

**Comment by DevVersion** [comment]
I've spotted the issue :smile: 

You are using Angular's Strict DI here
```js
  app.config(['$stateProvider', '$urlRouterProvider', stateParams])

  function stateParams($stateProvider, $urlRouterProvider, $mdIconProvider, $mdThemingProvider) {
```
and the `$mdThemingProvider` is undefined because you're not specifying it in the DI array.

To fix your issue, you just need to add it to the DI array - Like so:
```js
['$stateProvider', '$urlRouterProvider', '$mdIconProvider', '$mdThemingProvider', stateParams]
```

Notice: you're also missing the `$mdIconProvider` here.

**Comment by amanuel2** [comment]
How did i.... Wow @DevVersion Sorry for bieng the most dummest person on earth.

**Comment by amanuel2** [comment]
How did i...... Omg one of my dum mistakes..

**Comment by DevVersion** [comment]
@amanuel2 No worries :) - btw: this also fixes your other issue, with the CryptoProvider (https://github.com/middleout/angular-cryptography/issues/13)

**Comment by ThomasBurleson** [comment]
Also - I do not see where you specify the ngMaterial dependency:

```js
 var app = angular.module('ForumApp');
       app.config(['$stateProvider', '$urlRouterProvider', stateParams])
```

should be 

```js
 var app = angular.module( 'ForumApp', ['ngMaterial'] );
       app.config(['$stateProvider', '$urlRouterProvider', stateParams])
```

**Comment by amanuel2** [comment]
@ThomasBurleson you do not because thats in my script.js (main file) ... 

```
(function(angular) {
  var app = angular.module('ForumApp',

    [
        'ui.router',
        'ngMaterial',
        'firebase',
        'ngMessages',
        'mdo-angular-cryptography',
        'material.svgAssetsCache',
        'angularjs-crypto',
        'ngMdIcons'
    ]
)
})(angular);
```
