### ISSUE TITLE
$mdToast is not dismissed

### ISSUE THREAD

**Issue by joelhdzfdz** [angular/material#929]
Displaying the toast

```js
            $mdToast.show({
                controller: 'toastController',
                templateUrl: '../../views/toastTemplates/success.html',
                hideDelay: 6000,
                position: 'top right'
            });
```
The template 

```html
    <md-toast>
        <span flex>Success</span>
        <md-button ng-click="closeToast()">
            Close
        </md-button>
    </md-toast>
```

The closeToast() in the toast controller

```js
        $scope.closeToast = function() {
            $mdToast.hide();
        };
```
As you can see I'm doing what is done in the angular material demos page, I'm running the latest release, the toast is displayed but after doing so I get the error

```console
    TypeError: undefined is not a function
        at Object.onRemove (http://localhost:9000/bower_components/angular-material/angular-material.js:5434:15)
        at Object.InterimElement.self.remove (http://localhost:9000/bower_components/angular-material/angular-material.js:1082:31)
        at Object.cancel (http://localhost:9000/bower_components/angular-material/angular-material.js:1013:42)
        at Object.show (http://localhost:9000/bower_components/angular-material/angular-material.js:967:19)
        at Object.showInterimElement [as show] (http://localhost:9000/bower_components/angular-material/angular-material.js:910:38)
        at http://localhost:9000/scripts/userManagement/main.controller.js:24:22
        at http://localhost:9000/bower_components/angular/angular.js:13220:52
        at Scope.$eval (http://localhost:9000/bower_components/angular/angular.js:14353:28)
        at Scope.$digest (http://localhost:9000/bower_components/angular/angular.js:14169:31)
        at Scope.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2558:23)
```

Where

    `http://localhost:9000/scripts/userManagement/main.controller.js:24:22`

is the `$mdToast.show()` function, after this the toast is never dismissed.

**Comment by ajoslin** [comment]
Our `Hammer` instance doesn't have a `destroy` method, because the wrong version of HammerJS is being used.

Be sure to use version 2.0+.
