### ISSUE TITLE
Unit tests in release/1.1.1 fail

### ISSUE THREAD

**Issue by kevinmerckx** [angular/material#9658]
**Actual Behavior**:
 -  `What is the issue? *`
Unit tests on minified source fail on the branch release/1.1.1

 -  `What is the expected behavior?`
All unit tests should pass.

**CodePen** (or steps to reproduce the issue): *
 -  `git clone git@github.com:angular/material.git material && cd material`
 -  `npm install`
-   `gulp karma`

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version: 1.1.1`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: OSX10.11.6`
 -  `Stack Traces:`
 -  `Angular Material Version:` 1.1.1

```
Chrome 53.0.2785 (Mac OS X 10.11.6) $mdBottomSheet service #build() should close when `escapeToClose == true` FAILED
	Expected 1 to be 0.
	    at Object.<anonymous> (src/components/bottomSheet/bottom-sheet.spec.js:137:55)
	    at Object.invoke (node_modules/angular/angular.js:4718:19)
	    at Object.workFn (node_modules/angular-mocks/angular-mocks.js:3085:20)
Chrome 53.0.2785 (Mac OS X 10.11.6) $mdBottomSheet service #build() should close when navigation fires `scope.$destroy()` FAILED
	Expected 1 to be 0.
	    at Object.<anonymous> (src/components/bottomSheet/bottom-sheet.spec.js:173:55)
	    at Object.invoke (node_modules/angular/angular.js:4718:19)
	    at Object.workFn (node_modules/angular-mocks/angular-mocks.js:3085:20)
Chrome 53.0.2785 (Mac OS X 10.11.6) $mdPanel promises logic: should resolve when opening/closing FAILED
	Expected false to be true.
	    at Object.<anonymous> (src/components/panel/panel.spec.js:177:28)
	Expected false to be true.
	    at Object.<anonymous> (src/components/panel/panel.spec.js:185:29)
	Expected true to equal false.
	    at Object.<anonymous> (src/components/panel/panel.spec.js:186:35)
	Expected ".md-panel-outer-wrapper" not to match element(s), but found 1 items in the DOM
	    at Object.<anonymous> (src/components/panel/panel.spec.js:187:39)
Chrome 53.0.2785 (Mac OS X 10.11.6) $mdPanel promises logic: should reject on detach when closing FAILED
	Expected false to be true.
	    at Object.<anonymous> (src/components/panel/panel.spec.js:302:29)
Chrome 53.0.2785 (Mac OS X 10.11.6) $mdPanel promises logic: should handle calling open multiple times FAILED
	Expected false to be true.
	    at Object.<anonymous> (src/components/panel/panel.spec.js:322:24)
Chrome 53.0.2785 (Mac OS X 10.11.6) $mdPanel config options: should show backdrop when hasBackdrop=true FAILED
	Expected "._md-panel-backdrop" not to match element(s), but found 1 items in the DOM
	    at Object.<anonymous> (src/components/panel/panel.spec.js:642:34)
Chrome 53.0.2785 (Mac OS X 10.11.6) $mdPanel config options: should close when clickOutsideToClose and hasBackdrop are set to true FAILED
	TypeError: Cannot set property 'close' of null
	    at Object.<anonymous> (src/components/panel/panel.spec.js:660:26)
Chrome 53.0.2785 (Mac OS X 10.11.6) mdSidenav directive should focus sidenav on open FAILED
	Expected undefined to be HTMLNode.
	    at Object.<anonymous> (src/components/sidenav/sidenav.spec.js:88:39)
	    at Object.invoke (node_modules/angular/angular.js:4718:19)
	    at Object.workFn (node_modules/angular-mocks/angular-mocks.js:3085:20)
Chrome 53.0.2785 (Mac OS X 10.11.6) mdSidenav directive should focus child with md-sidenav-focus FAILED
	Expected undefined to be HTMLNode.
	    at Object.<anonymous> (src/components/sidenav/sidenav.spec.js:106:39)
	    at Object.invoke (node_modules/angular/angular.js:4718:19)
	    at Object.workFn (node_modules/angular-mocks/angular-mocks.js:3085:20)
Chrome 53.0.2785 (Mac OS X 10.11.6) mdSidenav directive should focus child with md-autofocus FAILED
	Expected undefined to be HTMLNode.
	    at Object.<anonymous> (src/components/sidenav/sidenav.spec.js:124:39)
	    at Object.invoke (node_modules/angular/angular.js:4718:19)
	    at Object.workFn (node_modules/angular-mocks/angular-mocks.js:3085:20)
Chrome 53.0.2785 (Mac OS X 10.11.6) mdSidenav directive should focus on last md-sidenav-focus element FAILED
	Expected undefined to be HTMLNode.
	    at Object.<anonymous> (src/components/sidenav/sidenav.spec.js:143:39)
	    at Object.invoke (node_modules/angular/angular.js:4718:19)
	    at Object.workFn (node_modules/angular-mocks/angular-mocks.js:3085:20)
Chrome 53.0.2785 (Mac OS X 10.11.6) mdSidenav directive should trigger a resize event when opening FAILED
	Expected spy callback to have been called.
	    at Object.<anonymous> (src/components/sidenav/sidenav.spec.js:178:30)
	    at Object.invoke (node_modules/angular/angular.js:4718:19)
	    at Object.workFn (node_modules/angular-mocks/angular-mocks.js:3085:20)
```

**Comment by DevVersion** [comment]
Not sure about this, but the tests are succeeding on `master` so the 1.1.1 branch is pretty uninteresting.

**Comment by kevinmerckx** [comment]
If it's a release, the unit tests should pass. Shouldn't they? I've also tried on `master`, the same unit tests fail

**Comment by DevVersion** [comment]
Yeah the tests should definitely pass for releases, but the release is kind of `past` and there were a few changes in `master` which could theoretically fix the aforementioned issue with the unit tests.

I can not reproduce this on my end. Also TravisCI runs fine with the tests in `master`..
