### ISSUE TITLE
chore: Error running the `jshint` task

### ISSUE THREAD

**Issue by gkalpak** [angular/material#982]
When trying to run `gulp jshint` I get the following error:

```
[18:21:44] TypeError: Cannot read property 'js' of undefined
    at Gulp.gulp.task.karmaConfig.singleRun (...\gulpfile.js:120:22)
    at module.exports (...\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (...\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (...\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (...\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at ...\npm\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

It's failing on this line:

    buildConfig.paths.js.concat(buildConfig.paths.test)

Indeed there doesn't seem to be a `paths` property in `buildConfig` (but I might be missing something).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
